version: '3'

volumes:
  db_data: {}

services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: jackhammer_production
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    restart: always
    volumes:
      - db_data:/usr/local/bin/mysql
  web:
    build: ./web
    depends_on:
      - db
      - redis
    environment:
      MYSQL_DB: jackhammer_production
      MYSQL_HOST: db
      MYSQL_PASSWORD: root
      MYSQL_USER: root
      RAILS_ENV: production
      RAILS_SERVE_STATIC_FILES: 'true'
      REDIS_URL: redis://redis:6379
      SECRET_KEY_BASE: 454ab84a2554a5e715db90c7560a06d8a20811d614e7313de05495ecdeac9614c4c3d263df1a5892b92d6c32ea06d4defbd2492c598e8295f89b8b316db25842
    ports:
      - "5000:3000"
  redis:
    image: redis
    ports:
      - "6379"
